name: inter_knot
description: 绳网是一个游戏、技术交流平台
publish_to: none
version: 0.3.0+1
repository: https://github.com/yinengbei/inter-knot

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  desktop_drop: ^0.5.0
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_gen: ^5.6.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^11.5.0
  flutter_quill_extensions: ^11.0.0
  flutter_widget_from_html: ^0.17.1
  gal: ^2.3.2
  get: ^4.6.6
  get_storage: ^2.1.1
  html: ^0.15.4
  image_picker: ^1.1.2
  intl: ^0.20.2
  logger: ^2.4.0
  markdown: ^7.3.0
  markdown_quill: ^4.3.0
  markdown_widget: 2.3.2+8
  photo_view: ^0.15.0
  shared_preferences: ^2.3.2
  universal_html: ^2.3.0
  url_launcher: ^6.3.0
  waterfall_flow: ^3.0.3
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.6.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: icon.webp
  web:
    generate: true
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: ZhCn
      fonts:
        - asset: assets/fonts/zh-cn.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.woff2

msix_config:
  display_name: Inter Knot
  publisher_display_name: tiwat
  identity_name: com.tiwat.inter-knot
  msix_version: 1.0.0.0
  logo_path: icon.webp
  capabilities: internetClient
  languages: zh-CN, zh-TC, en-US
